# Generated by Django 5.0.4 on 2024-05-25 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0004_remove_organization_name_organization_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="description",
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name="organization",
            name="name",
            field=models.CharField(default=None, max_length=255),
        ),
    ]
