# Generated by Django 5.0.4 on 2024-05-25 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0007_participant"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="participant",
            name="event",
        ),
        migrations.RemoveField(
            model_name="participant",
            name="user",
        ),
    ]
