# Generated by Django 5.0.4 on 2024-05-26 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0009_participant_event_participant_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participant",
            name="booking_id",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
